# -*- coding: utf-8 -*-
"""Script_JSON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5DS4GSuDUaqUvV2g0M60iQU0Qb-FO3E
"""

import numpy as np
import pandas as pd
import re 
class Global_Format_Json:
  def Cleaning_process(self,df):
    df=df.drop_duplicates()
    df1=pd.DataFrame()
    k=0
    list11=[]
    list22=[]
    list33=[]
    l=np.nan

    for i in df.values:
      k=k+1
      g=i[0].split()
      for j in range(0,len(g)):
        if j==0:
          list33.append(int(k))
        else:
          list33.append(l)
        list1=[]
        list2=[]
       
        a=re.findall('.+?(?=###)',g[j])
        b=re.findall('(?<=\###).*',g[j])
        list1.append(a[0])
        list2.append(b[0])
        list11.append(list1[0])
        list22.append(list2[0])
    df1['sentences']=list33
    df1['words']=list11
    df1['tags']=list22
    df1['sentences'].replace(np.nan, ' ', inplace=True)
    list6=[]
    for i in df1['tags'].values:
      for j in i:
        if j=='#':
          print(i)
        else:

          break
      list6.append(i)

    a=set(list6)
    c=[]
    for i in a:
      b=[]
      for j in i:
        b.append(j)
      if '#'  in b:
        c.append(i)
  
    for i in c:
      df1=df1[df1.tags != i]
      list3=[]
      list4=[]  
      c=0
    
    df1=df1.reset_index()
    df1.drop('index',axis=1)    
    list3=[]
    list4=[]
    c=0
    for i in range(0,len(df1['sentences'])):
      if (type(df1['sentences'][i])==float):
        list3.append(list4)
        list4=[]   
        c=c+1
        list4.append((df1['words'][i],df1['tags'][i]))
      if  (type(df1['sentences'][i])==str):
        list4.append((df1['words'][i],df1['tags'][i]))
    return(list3,df1)

  def entity_creation(self,i):
    text=[]
    for j in i:
      text.append(j[0])
    text1=' '.join(text)
    dict2={}
    dict2={}
    list22=[]
    list2=[]
    j=0
    while (j<len(i)):
      dict_s={}
      if i[j][1]!='O':

        entity=i[j][1]  
        list_val=[i[j][0]]
        if j<=len(i):
          P=j
          for k in range(j+1,len(i)):
            if entity==i[k][1]:
              list_val.append(i[k][0])
              dict_s['entity']=entity
              dict_s['value']=' '.join(list_val)
              dict_s['start_token']=P
              dict_s['start_char']=text1.index(' '.join(list_val))
              dict_s['end_char']=text1.index(' '.join(list_val))+len(' '.join(list_val))
              j=k
              dict_s['End_token']=k
              # print(dict_s)
              j=j+1
              # print(j)
              # print("yes",dict_s)
            else:
              break
            
        if j<len(i) and i[j][1]!='O':
          dict_s['entity']=i[j][1]
          dict_s['value']=' '.join(list_val)
          dict_s['start_token']=j
          dict_s['start_char']=text1.index(' '.join(list_val))
          dict_s['end_char']=text1.index(' '.join(list_val))+len(' '.join(list_val))
          dict_s['End_token']=j
          if i[j][1]=='-checkin' or i[j][1]=='-checkout':
             dict_s['General_Entity']='Date'
          elif i[j][1]=='-StarRate' and i[j][1]=='-NoOfTravellers' and i[j][1]=='-NoOfRoom':
             dict_s['General_Entity']='Number'
          else:
             dict_s['General_Entity']='others'
        list22.append(dict_s)
      j=j+1

    return(list22)
  
  def main(self,df):
    data_list,data_df=self.Cleaning_process(df)
    final_dict={}
    listFinal=[]
    for i in data_list[1:]:
      dict1={}
      text=[]
      list_intent=[]
      for k in range(1,int(i[0][0])+1):
         list_intent.append(i[k][0])
      dict1['intents']=list_intent  
      ent=[]
      # print(i)
      ent=self.entity_creation(i)
      for j in range(int(i[0][0])+1,len(i)):
        text.append(i[j][0])
      dict1['text']=' '.join(text)
      dict1['entity']=ent
      listFinal.append(dict1)
    final_dict['Dataset_hotel']=listFinal
    return final_dict


